HACK: gstreamer1.0-plugins-bad_1.16.2: remove PACKAGECONFIG gl
build fails with:
Run-time dependency gstreamer-gl-1.0 found: NO (tried pkgconfig and cmake)

gl is added to PACKAGECONFIG with:
${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'gl', '', d)

but in gstreamer1.0-plugins-base there is:

PACKAGECONFIG_GL ?= "${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'gles2 egl', '', d)}"

no opengl here.

After adding opengl to gstreamer1.0-plugins-base we get

ERROR: Nothing PROVIDES 'libglu' (but /home/jremmet/tmp/dunfell-next/sources/poky/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.16.2.bb DEPENDS on or otherwise requires it)

due to:
PACKAGECONFIG[opengl]       = ",,virtual/libgl libglu"

removing gl from PACKAGECONFIG will at least build.

Signed-off-by: Jan Remmet <j.remmet@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>