gtk+3: Remove virtual/mesa dependency for wayland on rk3288 machines
This is a dependency removal only for rk3288 based machines.

meta-gstreamer1.0 added gtk dependency for wayland builds in commit
  c35d927126d0 ("gstreamer1.0-plugins-bad: upgrade to version 1.12.0")
And gtk3+ adds a virtual/mesa dependency for wayland which fails with our
mali recipe.

Fixes:
ERROR: Nothing PROVIDES 'virtual/mesa' (but /home/egorov/yocto-builds/RK/sources/poky/meta/recipes-gnome/gtk+/gtk+3_3.20.9.bb DEPENDS on or otherwise requires it)

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>