recipes-qt: packagegroups: add nativesdk-qtdeclarative-tools
Without this additional package in nativesdk-packagegroup-qt5-toolchain-host,
we will run into an error if we use the SDK.
  Error:  ./sysroots/x86_64-phytecsdk-linux/usr/bin/qmlcachegen: not found

This file exists at another location as before (sumo branch).
sumo:    ./sysroots/aarch64-phytec-linux/usr/bin/qt5/qmlcachegen
warrior: ./sysroots/aarch64-phytec-linux/usr/bin/qmlcachegen

So it looks like there is done any change within QT itself,
where to search for this file. For now we can simply add this package,
which then will install the file additional under the searched path.
This way it is done by other people with the same issue.

Signed-off-by: Norbert Wesp <n.wesp@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>